export const translations = {
  pl: {
    'nav.services':      'Usługi',
    'nav.about':         'O nas',
    'nav.reviews':       'Opinie',
    'nav.contact':       'Kontakt',
    'nav.cta':           'Zarezerwuj',
    'hero.line1':        'SZTUKA',
    'hero.line2':        'PRECYZJI',
    'hero.line3':        'CIĘCIA',
    'hero.sub':          'Styl, klasa i atmosfera.',
    'hero.btn':          'Odkryj',
    'services.label':    'Nasze Usługi',
    'services.title_l1': 'Kunszt',
    'services.title_l2': 'Precyzji',
    's0.name':  'Strzyżenie',
    's0.desc':  'Dopasowane do Twojej twarzy. Rzeźbione do perfekcji.',
    's0.price': 'od 80 zł',
    's1.name':  'Broda',
    's1.desc':  'Czyste linie, wyrazisty kształt, trwałe wrażenie.',
    's1.price': 'od 70 zł',
    's2.name':  'Fade',
    's2.desc':  'Nowoczesne przejścia w różnych wariantach i stylach.',
    's2.price': 'od 90 zł',
    's3.name':  'Pakiet Combo',
    's3.desc':  'Strzyżenie + broda. Kompletne doświadczenie Kingston.',
    's3.price': 'od 120 zł',
    'about.label':    'Nasza Historia',
    'about.title_l1': 'Gdzie Rzemiosło',
    'about.title_l2': 'Spotyka Kulturę',
    'about.text': 'Kingston powstało z przekonania, że pielęgnacja to nie transakcja — to doświadczenie. Każde cięcie to rozmowa, każde golenie to ceremonia. Łączymy starą szkołę z nowoczesną precyzją, aby efekty mówiły za siebie zanim otworzysz usta.',
    'reviews.label':    'Opinie Klientów',
    'reviews.title_l1': 'Co Mówią',
    'reviews.title_l2': 'Nasi Klienci',
    'reviews.score':    '5.0',
    'reviews.count':    '400+ Opinii Google · 2000+ Booksy',
    'r0.name': 'Michał K.',
    'r0.text': '"Świetny barbershop! Atmosfera jak dawniej, nowoczesne podejście. Barber słucha dokładnie i zawsze perfekcyjnie."',
    'r0.date': '2 tygodnie temu',
    'r1.name': 'James W.',
    'r1.text': '"Amazing place! Great English service, professional staff, authentic atmosphere. Best haircut in Krakow!"',
    'r1.date': 'miesiąc temu',
    'r2.name': 'Piotr N.',
    'r2.text': '"Fantastycznie! Bilard podczas czekania, super klimat. Personel zna się na rzeczy."',
    'r2.date': '3 tygodnie temu',
    'cta.label': 'Zarezerwuj wizytę',
    'cta.line1': 'Twój',
    'cta.line2': 'Najlepszy',
    'cta.line3': 'Look',
    'cta.sub':   'Pon–Sob 09:00–21:00  ·  Niedz 10:00–20:00',
    'cta.btn':   'Zarezerwuj przez Booksy',
    'cta.phone': 'Zadzwoń: 510 018 118',
    'footer.address': 'Powstańców 86, Kraków — Nowa Huta',
    'footer.email':   'info@kingstonbarbershop.pl',
    'footer.copy':    '© 2025 Kingston Barbershop. Wszelkie prawa zastrzeżone.',
  },
  en: {
    'nav.services':      'Services',
    'nav.about':         'About',
    'nav.reviews':       'Reviews',
    'nav.contact':       'Contact',
    'nav.cta':           'Book Now',
    'hero.line1':        'THE ART',
    'hero.line2':        'OF THE',
    'hero.line3':        'CUT',
    'hero.sub':          'Premium grooming. Zero compromise.',
    'hero.btn':          'Discover',
    'services.label':    'Our Services',
    'services.title_l1': 'The Art',
    'services.title_l2': 'of Precision',
    's0.name':  "Men's Haircut",
    's0.desc':  'Tailored to your face. Sculpted to perfection.',
    's0.price': 'from €20',
    's1.name':  'Beard Grooming',
    's1.desc':  'Clean lines, defined shape, lasting impression.',
    's1.price': 'from €18',
    's2.name':  'Fade',
    's2.desc':  'Modern fade cuts in various variants and styles.',
    's2.price': 'from €22',
    's3.name':  'Combo Package',
    's3.desc':  'Haircut + beard. The complete Kingston experience.',
    's3.price': 'from €30',
    'about.label':    'Our Story',
    'about.title_l1': 'Where Craft',
    'about.title_l2': 'Meets Culture',
    'about.text': "Kingston was born from a conviction that grooming is not a transaction — it is an experience. Every cut is a conversation, every shave a ceremony. We combine old-world mastery with modern precision to deliver results that speak before you say a word.",
    'reviews.label':    'Client Reviews',
    'reviews.title_l1': 'What Our',
    'reviews.title_l2': 'Clients Say',
    'reviews.score':    '5.0',
    'reviews.count':    '400+ Google Reviews · 2000+ Booksy',
    'r0.name': 'Michał K.',
    'r0.text': '"Great barbershop! Old-school atmosphere, modern approach. The barber listens carefully and always delivers perfectly."',
    'r0.date': '2 weeks ago',
    'r1.name': 'James W.',
    'r1.text': '"Amazing place! Great English service, professional staff, authentic atmosphere. Best haircut in Krakow!"',
    'r1.date': '1 month ago',
    'r2.name': 'Piotr N.',
    'r2.text': '"Fantastic! Pool table while waiting, super masculine vibe. Staff really knows their craft."',
    'r2.date': '3 weeks ago',
    'cta.label': 'Book an appointment',
    'cta.line1': 'Your',
    'cta.line2': 'Best',
    'cta.line3': 'Look',
    'cta.sub':   'Mon–Sat 09:00–21:00  ·  Sun 10:00–20:00',
    'cta.btn':   'Book via Booksy',
    'cta.phone': 'Call: 510 018 118',
    'footer.address': 'Powstańców 86, Kraków — Nowa Huta',
    'footer.email':   'info@kingstonbarbershop.pl',
    'footer.copy':    '© 2025 Kingston Barbershop. All rights reserved.',
  },
};
